// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <string.h>
#include "equilibrium_angle_t.h"

static int __equilibrium_angle_t_hash_computed;
static uint64_t __equilibrium_angle_t_hash;

uint64_t __equilibrium_angle_t_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __equilibrium_angle_t_get_hash)
            return 0;

    __lcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = __equilibrium_angle_t_get_hash;
    (void) cp;

    uint64_t hash = (uint64_t)0x76352b3b9f2b80bcLL
         + __int64_t_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __int64_t_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __equilibrium_angle_t_get_hash(void)
{
    if (!__equilibrium_angle_t_hash_computed) {
        __equilibrium_angle_t_hash = (int64_t)__equilibrium_angle_t_hash_recursive(NULL);
        __equilibrium_angle_t_hash_computed = 1;
    }

    return __equilibrium_angle_t_hash;
}

int __equilibrium_angle_t_encode_array(void *buf, int offset, int maxlen, const equilibrium_angle_t *p, int elements)
{
    int pos = 0, element;
    int thislen;

    for (element = 0; element < elements; element++) {

        thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].utime), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].equilibrium_angle), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].set_equilibrium), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int equilibrium_angle_t_encode(void *buf, int offset, int maxlen, const equilibrium_angle_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __equilibrium_angle_t_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __equilibrium_angle_t_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __equilibrium_angle_t_encoded_array_size(const equilibrium_angle_t *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __int64_t_encoded_array_size(&(p[element].utime), 1);

        size += __float_encoded_array_size(&(p[element].equilibrium_angle), 1);

        size += __int64_t_encoded_array_size(&(p[element].set_equilibrium), 1);

    }
    return size;
}

int equilibrium_angle_t_encoded_size(const equilibrium_angle_t *p)
{
    return 8 + __equilibrium_angle_t_encoded_array_size(p, 1);
}

size_t equilibrium_angle_t_struct_size(void)
{
    return sizeof(equilibrium_angle_t);
}

int equilibrium_angle_t_num_fields(void)
{
    return 3;
}

int equilibrium_angle_t_get_field(const equilibrium_angle_t *p, int i, lcm_field_t *f)
{
    if (0 > i || i >= equilibrium_angle_t_num_fields())
        return 1;
    
    switch (i) {
    
        case 0: {
            f->name = "utime";
            f->type = LCM_FIELD_INT64_T;
            f->typestr = "int64_t";
            f->num_dim = 0;
            f->data = (void *) &p->utime;
            return 0;
        }
        
        case 1: {
            f->name = "equilibrium_angle";
            f->type = LCM_FIELD_FLOAT;
            f->typestr = "float";
            f->num_dim = 0;
            f->data = (void *) &p->equilibrium_angle;
            return 0;
        }
        
        case 2: {
            f->name = "set_equilibrium";
            f->type = LCM_FIELD_INT64_T;
            f->typestr = "int64_t";
            f->num_dim = 0;
            f->data = (void *) &p->set_equilibrium;
            return 0;
        }
        
        default:
            return 1;
    }
}

const lcm_type_info_t *equilibrium_angle_t_get_type_info(void)
{
    static int init = 0;
    static lcm_type_info_t typeinfo;
    if (!init) {
        typeinfo.encode         = (lcm_encode_t) equilibrium_angle_t_encode;
        typeinfo.decode         = (lcm_decode_t) equilibrium_angle_t_decode;
        typeinfo.decode_cleanup = (lcm_decode_cleanup_t) equilibrium_angle_t_decode_cleanup;
        typeinfo.encoded_size   = (lcm_encoded_size_t) equilibrium_angle_t_encoded_size;
        typeinfo.struct_size    = (lcm_struct_size_t)  equilibrium_angle_t_struct_size;
        typeinfo.num_fields     = (lcm_num_fields_t) equilibrium_angle_t_num_fields;
        typeinfo.get_field      = (lcm_get_field_t) equilibrium_angle_t_get_field;
        typeinfo.get_hash       = (lcm_get_hash_t) __equilibrium_angle_t_get_hash;
    }
    
    return &typeinfo;
}
int __equilibrium_angle_t_decode_array(const void *buf, int offset, int maxlen, equilibrium_angle_t *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].utime), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].equilibrium_angle), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].set_equilibrium), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __equilibrium_angle_t_decode_array_cleanup(equilibrium_angle_t *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int64_t_decode_array_cleanup(&(p[element].utime), 1);

        __float_decode_array_cleanup(&(p[element].equilibrium_angle), 1);

        __int64_t_decode_array_cleanup(&(p[element].set_equilibrium), 1);

    }
    return 0;
}

int equilibrium_angle_t_decode(const void *buf, int offset, int maxlen, equilibrium_angle_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __equilibrium_angle_t_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __equilibrium_angle_t_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int equilibrium_angle_t_decode_cleanup(equilibrium_angle_t *p)
{
    return __equilibrium_angle_t_decode_array_cleanup(p, 1);
}

int __equilibrium_angle_t_clone_array(const equilibrium_angle_t *p, equilibrium_angle_t *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int64_t_clone_array(&(p[element].utime), &(q[element].utime), 1);

        __float_clone_array(&(p[element].equilibrium_angle), &(q[element].equilibrium_angle), 1);

        __int64_t_clone_array(&(p[element].set_equilibrium), &(q[element].set_equilibrium), 1);

    }
    return 0;
}

equilibrium_angle_t *equilibrium_angle_t_copy(const equilibrium_angle_t *p)
{
    equilibrium_angle_t *q = (equilibrium_angle_t*) malloc(sizeof(equilibrium_angle_t));
    __equilibrium_angle_t_clone_array(p, q, 1);
    return q;
}

void equilibrium_angle_t_destroy(equilibrium_angle_t *p)
{
    __equilibrium_angle_t_decode_array_cleanup(p, 1);
    free(p);
}

int equilibrium_angle_t_publish(lcm_t *lc, const char *channel, const equilibrium_angle_t *p)
{
      int max_data_size = equilibrium_angle_t_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = equilibrium_angle_t_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _equilibrium_angle_t_subscription_t {
    equilibrium_angle_t_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void equilibrium_angle_t_handler_stub (const lcm_recv_buf_t *rbuf,
                            const char *channel, void *userdata)
{
    int status;
    equilibrium_angle_t p;
    memset(&p, 0, sizeof(equilibrium_angle_t));
    status = equilibrium_angle_t_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding equilibrium_angle_t!!!\n", status);
        return;
    }

    equilibrium_angle_t_subscription_t *h = (equilibrium_angle_t_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    equilibrium_angle_t_decode_cleanup (&p);
}

equilibrium_angle_t_subscription_t* equilibrium_angle_t_subscribe (lcm_t *lcm,
                    const char *channel,
                    equilibrium_angle_t_handler_t f, void *userdata)
{
    equilibrium_angle_t_subscription_t *n = (equilibrium_angle_t_subscription_t*)
                       malloc(sizeof(equilibrium_angle_t_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel,
                                 equilibrium_angle_t_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg equilibrium_angle_t LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int equilibrium_angle_t_subscription_set_queue_capacity (equilibrium_angle_t_subscription_t* subs,
                              int num_messages)
{
    return lcm_subscription_set_queue_capacity (subs->lc_h, num_messages);
}

int equilibrium_angle_t_unsubscribe(lcm_t *lcm, equilibrium_angle_t_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe equilibrium_angle_t_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

